# Generated by Django 4.2.9 on 2024-01-14 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_enclosure_description_enclosure_medium'),
        ('papers', '0002_status_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status_post_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='status',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feeds.post'),
        ),
    ]
