# Generated by Django 4.2.9 on 2024-01-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_status_created_at_status_status_post_id_status_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status_post_id',
            new_name='publication_id',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='json',
            new_name='response',
        ),
    ]
