# Generated by Django 5.1.1 on 2024-11-10 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_source_alt_url'),
        ('papers', '0004_rename_status_post_id_status_publication_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.post'),
        ),
    ]
