# Generated by Django 4.2.9 on 2024-01-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instance', models.CharField(max_length=50)),
                ('client_key', models.CharField(blank=True, max_length=50)),
                ('client_secret', models.CharField(blank=True, max_length=50)),
                ('access_token', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
