# Generated by Django 4.2.9 on 2024-01-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='instance',
            new_name='handle',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='service',
        ),
    ]
