# Generated by Django 4.2.9 on 2024-01-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_instance_client_handle_remove_client_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='handle',
            new_name='account',
        ),
    ]
