# Generated by Django 4.2.9 on 2024-01-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_handle_client_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='api_base_url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
