# Generated by Django 5.1.1 on 2024-11-10 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_alter_feed_name"),
        ("feeds", "0015_source_alt_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="source",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feeds.source",
            ),
        ),
    ]
