# Generated by Django 5.2.3 on 2025-06-28 10:19

from django.db import migrations


def update_site(apps, schema_editor):
    SiteModel = apps.get_model("sites", "Site")
    site, created = SiteModel.objects.get_or_create(id=1)
    site.name = "evodevo.brunovellutini.com"
    site.domain = "evodevo.brunovellutini.com"
    site.save()


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0006_feed_description"),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_site),
    ]
