# Generated by Django 5.2.3 on 2025-06-28 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0007_auto_20250628_1219"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created",
        ),
    ]
