# Generated by Django 5.2.3 on 2025-06-30 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0012_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statuses",
                to="bot.post",
            ),
        ),
    ]
