# Generated by Django 5.2.3 on 2025-07-01 06:06

from django.db import migrations


def create_statuses(apps, schema_editor):
    Post = apps.get_model("bot", "Post")
    Status = apps.get_model("bot", "Status")
    Client = apps.get_model("bot", "Client")

    mastodon_client, created = Client.objects.get_or_create(account="@evodevo_papers@biologists.social")

    for post in Post.objects.all():
        status = Status(
            post=post,
            client=mastodon_client,
            response=post.response,
            url=post.url,
            published=post.published,
        )
        status.save()


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0013_status_post"),
    ]

    operations = [
        migrations.RunPython(create_statuses),
    ]
