# Generated by Django 5.2.3 on 2025-07-01 06:32

from django.db import migrations


def update_statuses(apps, schema_editor):
    Status = apps.get_model("bot", "Status")

    for status in Status.objects.all():
        status.text = status.post.text
        status.created = status.post.created
        status.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_status_options_status_created_status_text'),
    ]

    operations = [
        migrations.RunPython(update_statuses),
    ]
