# Generated by Django 5.2.3 on 2025-07-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
