# Generated by Django 5.2.3 on 2025-07-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0019_status_unique_status_per_client_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="response",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
