# Generated by Django 5.2.3 on 2025-07-05 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0021_auto_20250705_2053"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="published",
        ),
        migrations.RemoveField(
            model_name="post",
            name="response",
        ),
        migrations.RemoveField(
            model_name="post",
            name="text",
        ),
        migrations.RemoveField(
            model_name="post",
            name="url",
        ),
    ]
