# Generated by Django 5.2.3 on 2025-07-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0022_remove_post_published_remove_post_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.TextField(blank=True),
        ),
    ]
