# Generated by Django 5.2.3 on 2025-07-06 09:13

from django.db import migrations


def add_post_title_link(apps, schema_editor):
    Post = apps.get_model("bot", "Post")

    for post in Post.objects.all():
        if post.entry:
            post.title = post.entry.title
            post.link = post.entry.link
            post.save()


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0023_post_link_post_title"),
    ]

    operations = [
        migrations.RunPython(add_post_title_link),
    ]
