# Generated by Django 5.2.3 on 2025-07-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_rename_published_status_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
