# Generated by Django 5.2.3 on 2025-07-06 09:46

from django.db import migrations


def update_published(apps, schema_editor):
    Status = apps.get_model("bot", "Status")

    for status in Status.objects.all():
        if status.is_published:
            status.published = status.created
            status.save()


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0026_status_published"),
    ]

    operations = [
        migrations.RunPython(update_published),
    ]
