# Generated by Django 5.2.3 on 2025-07-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0029_auto_20250706_1528"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="status",
            constraint=models.UniqueConstraint(
                fields=("post", "client"), name="unique_status_per_post_client"
            ),
        ),
    ]
