# Generated by Django 5.2.3 on 2025-07-06 13:41

from django.db import migrations


def create_statuses(apps, schema_editor):
    Post = apps.get_model("bot", "Post")
    Client = apps.get_model("bot", "Client")
    Status = apps.get_model("bot", "Status")

    for post in Post.objects.all():
        for client in Client.objects.filter(is_active=True):
            status, created = Status.objects.get_or_create(post=post, client=client)
            status.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0030_status_unique_status_per_post_client'),
    ]

    operations = [
        migrations.RunPython(create_statuses),
    ]
