# Generated by Django 5.2.3 on 2025-07-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0032_alter_post_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
    ]
