# Generated by Django 5.2.3 on 2025-08-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0034_auto_20250706_1631"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
