# Generated by Django 5.2.3 on 2025-08-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0035_feed_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
