# Generated by Django 5.2.3 on 2025-08-29 21:08

from django.db import migrations


def update_post_created_timestamp(apps, schema_editor):
    Post = apps.get_model("bot", "Post")

    for post in Post.objects.all():
        post.created = post.entry.created
        post.save()


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0037_alter_post_created"),
    ]

    operations = [
        migrations.RunPython(update_post_created_timestamp),
    ]
