# Generated by Django 5.2.6 on 2025-09-13 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0039_alter_status_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="created",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
