# Generated by Django 5.2.6 on 2025-09-13 19:58

from django.db import migrations


def copy_feed_info(apps, schema_editor):
    Post = apps.get_model("bot", "Post")

    for post in Post.objects.all():
        post.feed = post.entry.source.feed
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0041_post_feed'),
    ]

    operations = [
        migrations.RunPython(copy_feed_info),
    ]
