# Generated by Django 5.1.1 on 2024-11-10 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        ('feeds', '0015_source_alt_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('source', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.source')),
            ],
        ),
    ]
