# Generated by Django 5.1.1 on 2024-11-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_feed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
